# file: roles/common/upgrade.yml

- name: create a yum repo file for an unreleased RHEL 8 compose - BaseOS
  yum_repository:
    file: rhel8_beta
    name: rhel8_beta_baseos
    description: Unreleased RHEL 8 Compose - BaseOS
    baseurl: "{{ rhel8_beta_baseurl }}"
    gpgcheck: no
  when: rhel8_beta_baseurl is defined and ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8
  tags: rhel8_beta

- name: create a yum repo file for an unreleased RHEL 8 compose - AppStream
  yum_repository:
    file: rhel8_beta
    name: rhel8_beta_appstream
    description: Unreleased RHEL 8 Compose - AppStream
    baseurl: "{{ rhel8_beta_baseurl | replace('BaseOS', 'AppStream')}}"
    gpgcheck: no
  when: rhel8_beta_baseurl is defined and "'BaseOS' in rhel8_beta_baseurl" and ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8
  tags: rhel8_beta

- name: create a yum repo file for an unreleased RHEL 9 compose - BaseOS
  yum_repository:
    file: rhel9_beta
    name: rhel9_beta_baseos
    description: Unreleased RHEL 9 Compose - BaseOS
    baseurl: "{{ rhel9_beta_baseurl }}"
    gpgcheck: no
  when: rhel9_beta_baseurl is defined and ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 9
  tags: rhel9_beta

- name: create a yum repo file for an unreleased RHEL 9 compose - AppStream
  yum_repository:
    file: rhel9_beta
    name: rhel9_beta_appstream
    description: Unreleased RHEL 9 Compose - AppStream
    baseurl: "{{ rhel9_beta_baseurl | replace('BaseOS', 'AppStream')}}"
    gpgcheck: no
  when: rhel9_beta_baseurl is defined and "'BaseOS' in rhel9_beta_baseurl" and ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 9
  tags: rhel9_beta

- name: create a yum repo file for an unreleased RHEL 10 compose - BaseOS
  yum_repository:
    file: rhel10_beta
    name: rhel10_beta_baseos
    description: Unreleased RHEL 10 Compose - BaseOS
    baseurl: "{{ rhel10_beta_baseurl }}"
    gpgcheck: no
  when: rhel10_beta_baseurl is defined and ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 10
  tags: rhel10_beta

- name: create a yum repo file for an unreleased RHEL 10 compose - AppStream
  yum_repository:
    file: rhel10_beta
    name: rhel10_beta_appstream
    description: Unreleased RHEL 10 Compose - AppStream
    baseurl: "{{ rhel10_beta_baseurl | replace('BaseOS', 'AppStream')}}"
    gpgcheck: no
  when: rhel10_beta_baseurl is defined and "'BaseOS' in rhel10_beta_baseurl" and ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 10
  tags: rhel10_beta

- name: update packages
  package:
    name: '*'
    state: latest
    update_cache: yes
    update_only: yes
  when: (upgrade_all_pkg | default(False) | bool) or
        (rhel8_beta_baseurl is defined and ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8) or
        (rhel9_beta_baseurl is defined and ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 9) or
        (rhel10_beta_baseurl is defined and ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 10)
  tags: upgrade_all_pkg,rhel8_beta,rhel9_beta,rhel10_beta

- name: check if rebooting is needed
  command: needs-restarting -r
  register: needs_restarting
  failed_when: needs_restarting.rc not in [0, 1]

- name: reboot after updating, if needed
  reboot:
  when: needs_restarting.rc == 1
  tags: upgrade_all_pkg,rhel8_beta,rhel9_beta
